### PR TITLE
Speed up pow by 4x or more

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by dpsanders** [comment]
Tests will fail until `pow` and `^` are swapped over.

**Comment by lbenet** [comment]
I've taken a look on this PR, and must begin saying that I understand the motivation, but I am not yet convinced that we should sacrifice tightness for speed; see #14.

As it was discussed in #103, current `^` allocates since we must play with `big53`. The question is if intercepting small powers can help us here?

Regarding the infimum and supremum of an empty interval, see [this comment](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/232#issuecomment-424948383); we are currently following the standard on this, so this shouldn't be changed. Reverting the changes ([here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/210/files#diff-d9d17fed755178cc4f7291ba34870545R285) and [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/210/files#diff-d9d17fed755178cc4f7291ba34870545R291)) in arithmetic.jl allows some tests to pass.

Very nice tricks for `fast_sqrt`. The question is how does the diameter of `Interval(fast_sqrt(a.lo , RoundDown)), fast_sqrt(a.hi , RoundUp))` compare with the results for `^(a, 0.5)` and `pow(a, 0.5)`?

**Comment by dpsanders** [comment]
The fast version of `sqrt` is now in `FastRounding` and will be used automatically once https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/230 is merged. The fast version is (supposed to) give exactly the same result as the slow version.

The fast powers in this PR give a result that is "almost" as tight as the terribly slow correctly-rounded version - for higher powers they will be less tight, since more squarings are required. In particular, squares (`x^2`) will give exactly the same result as now (but repeated squares may start losing a few ulps of accuracy).

I really think it's urgent that we make this change. Tight powers will still be available via `pow`. We could provide a way for automatically using tight powers instead, but I'm not sure what the API should look like (there are early open issues for this, e.g. #14 that you cited).

**Comment by dpsanders** [comment]
I have been using fast powers for a few months now. 
The difference in speed and allocations is like night and day. There is no question in my mind that we *must* make fast powers the default (but provide a mechanism to change to tight-but-slow powers).

**Comment by lbenet** [comment]
Tests are failing; I guess those that fail are related to `^`, and they should be using `pow`, right?

**Comment by dpsanders** [comment]
Yes, exactly.

**Comment by dpsanders** [comment]
That will require changes to itf1788. I think I have those in a branch somewhere.

**Comment by lbenet** [comment]
I guess the same holds; instead of using `^` they should use `pow`...

**Comment by mforets** [comment]
Is there a chance of getting this function in `master` but with another name, eg. `fast_pow(a, n)`?

**Comment by dpsanders** [comment]
It is already there with the name `pow`,  I believe?

**Comment by mforets** [comment]
I thought this branch gives a faster `pow` than master but it hasn't been resolved yet because it sacrifices tightness for speed. On `master` i measure ~1us for `Interval(0, 1)^2`, so i was assuming that it's using the "slow" version (?).

**Comment by mforets** [comment]
.. so if that's the case i was just proposing to export the "fast" version, possibly with a different name, keeping the slow one as default.

**Comment by dpsanders** [comment]
I get this on master:
```jl
julia> using BenchmarkTools, IntervalArithmetic
[ Info: Precompiling IntervalArithmetic [d1acc4aa-44c8-5952-acd4-ba5d80a2a253]

julia> @btime $(Ref(X))[]^2^C

julia> X = 0..1
[0, 1]

julia> @btime $(Ref(X))[]^2
  673.264 ns (29 allocations: 1.25 KiB)
[0, 1]

julia> @btime pow($(Ref(X))[], 2)
  30.811 ns (0 allocations: 0 bytes)
[0, 1]
```

But yes you're right, the `nonrecursive_powers` branch speeds this up by 3x.

**Comment by mforets** [comment]
Oh, i see what you mean know. I was missing that there's already a difference between `pow(a, n)` and `a^n`, and it's in the [docs](https://juliaintervals.github.io/IntervalArithmetic.jl/latest/api/#IntervalArithmetic.pow-Tuple{Interval,Integer})... 

> But yes you're right, the nonrecursive_powers branch speeds this up by 3x.

Alright, i will keep it in mind. Thanks!

**Comment by dpsanders** [comment]
We should definitely update `pow` to use the fast version, and then provide a way to use that instead of `^`.

**Comment by lbenet** [comment]
I agree with @mforets that this should be in master with another name (`fast_pow`), without touching the current `pow` for compatibility with the standard.

@dpsanders Do you have time to address the conflicts with the files currently in master?

**Comment by dpsanders** [comment]
Yes we should definitely incorporate the latest version into base in the `pow` function.

**Comment by OlivierHnt** [comment]
Solved in PR #593.

**Pull request closed without merging**
