### PR TITLE
Completes mpfi.jl and fi.lib.jl

### PR DESCRIPTION
**Pull request by krish8484**
Added cot, coth, csc, csch, sec and sech for intervals with corresponding tests from ITF1788 suite(mpfi.jl and fi_lib.jl)

### CODE REVIEW

**Comment by dpsanders** [comment]
This looks nice, thanks!

It would be great to add versions of these functions in the `:accurate` rounding mode that do not use MPFR, but just use the definition of the functions as the inverse of other trig functions etc.

**Comment by dpsanders** [comment]
That can also be a separate PR if this is ready?

**Comment by krish8484** [comment]
Yes, this is ready. I will work on adding these functions  in `:accurate` rounding mode in another one.

**Comment by dpsanders** [comment]
This looks good, apart from `cot` near pi/2.

**Comment by krish8484** [comment]
I reckon you were on a different branch

Master
```
julia> cot(1.5..1.6)
[-∞, ∞]
```

This Branch
```
julia> cot(1.5..1.6)
[-0.029212, 0.0709149]
```

**Comment by dpsanders** [comment]
Apologies, I think you're right that I must have had the wrong branch checked out.
`cot` indeed does seem to work.

Thanks a lot!

**Pull request merged**
