### PR TITLE
Fixes Interval-Boolean multiplication on Windows

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR fixes the error noticed in https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/188#issue-350628965.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks for the PR. 

I suggest to include some tests, precisely to catch those situations. A good start is the one that lead to #188

**Comment by lbenet** [comment]
Incidentally, I just noticed that current checks of travis and appveyor do not check Julia 0.7; they do it for Julia 1.0.

**Comment by mohamed82008** [comment]
But the error is only on Windows and Travis doesn't check Windows.

**Comment by lbenet** [comment]
See #190

**Comment by mohamed82008** [comment]
Hmm the error is already there https://ci.appveyor.com/project/dpsanders/intervalarithmetic-jl/build/1.0.117/job/qufll6qvubwxghqp#L176. I will setup appveyor for Windows like that PR then.

**Comment by lbenet** [comment]
I am no expert in appveyor or travis. However, I think there are still some problems to deal with. Can you check that *locally* tests pass?

**Comment by mohamed82008** [comment]
Rebased, let's if the error goes away or not.

**Comment by mohamed82008** [comment]
https://ci.appveyor.com/project/dpsanders/intervalarithmetic-jl/build/1.0.118/job/d70odm4dem5m28ar#L175

These tests now pass on Windows.

**Comment by lbenet** [comment]
So do you understand the `ayan2` problem?

**Comment by mohamed82008** [comment]
This is the offending line:
```julia
julia> atan2(@interval(0.0, 1.0), @biginterval(0.0))
┌ Warning: `atan2(y, x)` is deprecated, use `atan(y, x)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
ERROR: StackOverflowError:
```

**Comment by mohamed82008** [comment]
Julia is not finding https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/cab2433d6719899c38c0c3514fc935208614bdd0/src/intervals/trigonometric.jl#L207 so it keeps infinitely calling https://github.com/JuliaLang/julia/blob/72af6204a7fa448dd1bdc38305e78533b4a83040/base/math.jl#L559. Calling the deprecated `atan2` makes a warning then calls the replacement `atan` which is not overloaded by `IntervalArithmetic` so it causes the infinite recursion as `atan(y::Real, x::Real)` is the most specific method when `y` and `x` are `Interval{BigFloat}`. Changing the name of the method to `atan` fixes the error.

**Comment by dpsanders** [comment]
Thanks! Could you send a PR for that change, please?

**Comment by dpsanders** [comment]
Thanks. I guess these should be too separate PRs, though.

**Comment by dpsanders** [comment]
@lbenet Do you know what is going on with the `bisect` tests?

**Comment by lbenet** [comment]
Actually, I don't know. 

I've been trying to get tests pass, but somehow there are too many things which are breaking or broken in Julia 0.7.0.

**Comment by mohamed82008** [comment]
Separate PRs made. Both rebased on https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/190 so either close #190 or merge it first.

**Comment by lbenet** [comment]
I think we should tag a version (0.14.1) for whatever is in master now, as the last version which runs in Julia 0.6, and then bump into 0.7.0. 

I think this imposes (at least) some changes around: 
- ValidatedNumerics, should be tagged to run in Julia 0.6 with ValidatedNumerics.jl up to (but probably not including 0.14.0). 
- We should also tag a version (v0.7.0?) of CRlibm.jl which again will be the last to work in Julia 0.6.x

**Comment by lbenet** [comment]
So how do we proceed?

**Comment by dpsanders** [comment]
Is there any breaking change on master? If so, then the new tagged version for Julia 0.6 should be 0.15.

The current version of CRlibm is the one that works for Julia 0.6 (except for the weird compilation problem reported recently), so I don't  think it needs another tag right now.

Maybe it would be useful to make an issue with the list of all the problems that need to be fixed for 0.7, so that we can fix them one by one.

**Comment by dpsanders** [comment]
As far as I can tell, master === v0.14, so there is no need for another release.

**Comment by dpsanders** [comment]
Included in #194.

**Comment by dpsanders** [comment]
Thanks!

**Pull request closed without merging**
