### PR TITLE
Add intro to interval arithmetic in docs

### PR DESCRIPTION
**Pull request by eeshan9815**
https://discourse.julialang.org/t/ann-intervalrootfinding-jl-for-finding-all-roots-of-a-multivariate-function/9515/29

@dpsanders I have made minor changes to the original content. How do I test the changes made to the docs?

### CODE REVIEW

**Comment by dpsanders** [comment]
You can run `julia make.jl` in the `docs` folder.

Code blocks should be [doctests](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/)

**Comment by dpsanders** [comment]
Merging this for now, thanks!

**Comment by dpsanders** [comment]
@lbenet Do you know how/when the docs get updated?

**Comment by lbenet** [comment]
As far as I remember, the *stable* docs get updated once we tag a new version, while the *latest* should correspond to what we have in master.

One problem is when you push skipping travis tests. Let me take a look...

**Comment by lbenet** [comment]
I don't know.... A simple workaround is to tag a new patch version (minor?) to force updating the docs.

**Pull request merged**
