### PR TITLE
0.6 / 0.7 deprecations

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by dpsanders** [comment]
There doesn't seem to be any way of using `@compat` to use the new style of syntax.
I think this will have to wait until we drop support for 0.5.

**Comment by lbenet** [comment]
I agree with you, and I think that is the general trend: keep the old syntax until dropping support for Julia 0.5.

This is related to https://github.com/JuliaIntervals/ValidatedNumerics.jl/pull/258

**Comment by lbenet** [comment]
Shall I push to this branch some commits which use the `where` syntax in the functions?

**Comment by lbenet** [comment]
Or shall I use a different PR?

**Comment by dpsanders** [comment]
Push to this PR is fine.

**Comment by lbenet** [comment]
I just pushed 4 new commits to have the `where` syntax in the functions. I'll let travis do its work, and if everything is ok, we should merge.

**Comment by lbenet** [comment]
Tests are passing. Merging this...

**Comment by lbenet** [comment]
I think everything is ready for 0.11.0...

**Comment by dpsanders** [comment]
Thanks!

**Comment by dpsanders** [comment]
Tagged 0.11.0!

**Pull request merged**
