### PR TITLE
Add compat bounds

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
This should allow automatic merging

**Comment by dpsanders** [comment]
I just released CRlibm 0.8; could you please update this to allow 0.7 and 0.8?

**Comment by dpsanders** [comment]
Also you will need to allow StaticArrays 0.8 through 0.12.

**Comment by lbenet** [comment]
Done! Let's see how travis and appveyor react now.

**Comment by lbenet** [comment]
@dpsanders This is ready. Shall I merge and, once merged, try to register v0.16.2?

**Comment by dpsanders** [comment]
Yes. You can just change the version in project.toml in this same PR.

**Comment by lbenet** [comment]
The version in Project.toml is 0.16.2; I think this is correct, right?

**Comment by dpsanders** [comment]
Ah OK, sorry, yes great.

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
