### PR TITLE
fix deprecations [femtocleaner]

### PR DESCRIPTION
**Pull request by KristofferC**
This is what I got when running FemtoCleaner locally @dpsanders

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot @KristofferC ! Tests pass, so I'll merge this right away!

**Comment by dpsanders** [comment]
But tests don't pass on 0.7...

**Comment by lbenet** [comment]
Sorry, i got excited by the green flags. I'll check this along the day. I don't think that the additions harm for v0.6...

**Comment by lbenet** [comment]
Or do you prefer to rever this?

**Comment by dpsanders** [comment]
No problem, it's fine to leave it since as you say all the changes also
work on 0.6.

**Comment by lbenet** [comment]
For the record, part of the problem (or rather a limitation) with the tests in Julia 0.7 is related to StaticArrays.jl:
```julia
ERROR: LoadError: LoadError: syntax: malformed expression
...
```

**Pull request merged**
