### PR TITLE
Fix subscriptify

### LINKED ISSUE #135: subscriptify not defined for Int32
Change the definition to accept Integer, not Int64.
This arose on Windows.

### PR DESCRIPTION
**Pull request by SebastianM-C**
Fix #135

### CODE REVIEW

**Comment by dpsanders** [comment]
Are you using

git rebase master

? You shouldn't be getting those merge commits.

**Comment by SebastianM-C** [comment]
I updated my fork to the latest version to have the same version. Is this not something that I should do?

**Comment by dpsanders** [comment]
I usually do something like

```
git checkout master
git pull

git checkout my-branch
git rebase master
git push -f
```

**Comment by SebastianM-C** [comment]
So I should delete my fork and try again?

**Comment by dpsanders** [comment]
No that's not necessary. 

What's the output of `git remote -v`?
There should be two remotes -- this repo, and your fork.

If that's the case, and assuming this repo is called `upstream`, you should do something like

```
git checkout master
git pull upstream master
git push -f
```
to update master of your fork to latest master of this repo.

Ah, I've just noticed that you're sending this PR from your master branch.
That's usually a bad idea -- you should create a new branch for each PR, exactly so that you can easily keep master synced with master from this repo.

Then do the `git rebase master` sequence that I specified above.

**Comment by SebastianM-C** [comment]
I created a PR from a separate branch which has only the required commit. I am closing this and will try to fix my master. Sorry for the trouble.

**Comment by dpsanders** [comment]
No problem, thanks!

**Pull request closed without merging**
