### PR TITLE
Add pow for interval^real and interval^interval

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
Tests are missing; otherwise, I think this is ready to be merged.

**Comment by dpsanders** [comment]
Yes, you're right, it needs tests.

**Comment by dpsanders** [comment]
Rebased. This is now ready.

**Comment by lbenet** [comment]
Yes, I agree that we should merge this; let's just allow the test to complete. Thanks!

**Comment by lbenet** [comment]
Simple curiosity: have you tried to see how many tests of the ITF1788 pass and how many fail, when using `pow` as a replacement for `^`?

**Comment by dpsanders** [comment]
No I haven't tried, but I expect that almost all will fail...

**Pull request merged**
