### PR TITLE
Get IntervalArithmetic.jl ready for Julia 1.0

### PR DESCRIPTION
**Pull request by dpsanders**
(Incorporates the previous PRs for 0.7.)

- [x] `setrounding` will be handled by https://github.com/JuliaIntervals/SetRounding.jl once it is registered (in process).

- [x] New iteration protocol.

- [x] Add `global` in loops in testsets

- [x] Reenable complex tests.  Complex powers do not work #198

### CODE REVIEW

**Comment by dpsanders** [comment]
Sorry, should have rebased instead of merging.

**Comment by dpsanders** [comment]
I suggest that we *don't*  squash when we merge this.

**Comment by dpsanders** [comment]
Tests are passing! ;)  Still a bit of work to do though.

**Comment by lbenet** [comment]
Note that deprecation warnings in CRlibm were solved; it is a question of tagging a new version.

**Comment by lbenet** [comment]
Nice work!

**Comment by lbenet** [comment]
I just checked that, except for a single test, all tests in `test/interval_tests/complex.jl` pass. The problematic one is `@test a^2 == -1`. I suggest to have the tests for complex numbers, and either comment the problematic case or use `@test_broken` for it.

**Comment by lbenet** [comment]
@mohamed82008 Have you check that tests pass in windows for this branch (`dps/0.7`)? 
If I recall some of the discussion, in spite of appveyor opinion, tests were failing in windows.

**Comment by mohamed82008** [comment]
Not yet. I will as soon as I'm infront of a computer.

**Comment by dpsanders** [comment]
@lbenet Great, let's do that then. Would you like to do it or shall I?

**Comment by mohamed82008** [comment]
Tests pass on my machine. I am only getting the `setrounding` warning.

**Comment by dpsanders** [comment]
The latest commit needs the next tagged version of CRlibm (in progress) and of SetRounding (to come).

**Comment by dpsanders** [comment]
All tests are passing on 0.7, 1.0 and nightly, on all platforms!
This is ready to merge. cc @lbenet

**Comment by lbenet** [comment]
Thanks a lot for the big effort!

I think we should first tag a last version which is compatible with Julia 0.6 of ValidatedNumerics.jl and the rest of the packages with the proper version, and then merge and tag this PR. See https://github.com/JuliaIntervals/ValidatedNumerics.jl/pull/285, whose tests should be working now.

**Comment by dpsanders** [comment]
There are no changes on master since v0.14.0, so we can treat v0.14.0 as the last version compatible with Julia 0.6.

**Comment by lbenet** [comment]
Shall we merge this and tag a new version (Julia 0.7 and 1.0 compatible only)?

**Comment by dpsanders** [comment]
Merging...

**Pull request merged**
