### PR TITLE
Fix cancelminus

### LINKED ISSUE #508: `cancelminus` specification
The following code
```julia
a = @interval(1e308, 1e308)
b = @interval(1e-308, 1e-308)
@show cancelminus(a, b)
```
prints
```
cancelminus(a, b) = [9.99999e+307, 1.00001e+308]
```
Is it really what the standard mandates?  Shouldn't it be `Interval(prevfloat(Inf), Inf)`?

### PR DESCRIPTION
**Pull request by lbenet**
Fixes #508

### CODE REVIEW

**Review by lucaferranti — APPROVED** [review]
LGTM, can you bump the project patch version?
Also, I think to understand that the corner case 2 wasn't covered in the ITF1788 test-suite, maybe we should test that somewhere?

**Comment by lbenet** [comment]
Thanks for your review @lucaferranti !

I think it is covered, at least in [this file](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/test/test_ITF1788/libieeep1788_cancel.jl), but I should look at it more careful. Now I can't look at this, but in the afternoon I'll check that and if needed, I add the needed tests.

**Comment by lucaferranti** [comment]
The file was testing the more extreme corner case `cancelminus([M, M], [-M, -M])` where `M = prevfloat(Inf)` [here]https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/test/test_ITF1788/libieeep1788_cancel.jl#L103) I think that case was manually captured by [this line](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/src/intervals/arithmetic.jl#L536) but that didn't generalize to other cases e.g. `M = 1e308` as reported in #508

**Comment by lbenet** [comment]
You are right Luca: the case `cancelminus([M,M], [-M,-M])` with `M` *sufficiently large* (such that `prevfloat(Inf) < 2M`), was not captured consistently by those lines. So I've added few more tests.

Once tests pass, I'll merge and tag the new version.

**Pull request merged**
