### PR TITLE
Import isadjoint when necessary

### LINKED ISSUE #360: Tests failling in nightly
I just noticed that tests are failing in nightly; see [this travis output](https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/jobs/648433766#L320). The problem seems to be that Base is *also* exporting `isdisjoint`, which makes that `the function is not unambiguously recognized. See also [NanosoldierReports](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2020-01/13/report.md) which runs daily, in the list of packages that failed previously.

### PR DESCRIPTION
**Pull request by dpsanders**
Fixes #360

### CODE REVIEW

**Comment by dpsanders** [comment]
This is ready.

**Comment by lbenet** [comment]
LGTM, thanks!

I think it is a good time to include tests using Julia 1.5 as well. Also, it is probably worth to update `Project.toml` to release a new (minor?) version.

**Comment by lbenet** [comment]
Thanks a lot! Merged.

**Comment by dpsanders** [comment]
There are no breaking changes so I made a patch version.

**Comment by lbenet** [comment]
I noticed, and agreed with your decision!

**Pull request merged**
