### PR TITLE
Avoid `convert` in `^` for literal powers

### LINKED ISSUE #618: Avoid `convert` to `Interval` in `^`
In current master:
```julia
julia> using IntervalArithmetic

julia> a = interval(1,2)
[1.0, 2.0]_com

julia> a^4
[1.0, 16.0]_com_NG
```
The *non-guaranteed* flag is disturbing. The problem arises from [these lines](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/946493a03a1c4535334956302ec7a2c9807e0d59/src/intervals/arithmetic/power.jl#L63C1-L66C74), which use `convert`. This, incidentally, does not respects the `PowerMode` in use.

### PR DESCRIPTION
**Pull request by lbenet**
Fix #618

### CODE REVIEW

**Comment by lbenet** [comment]
This is related to the test that fails:
```julia
julia> f(x)  = interval(2)^x
f (generic function with 1 method)

julia> f′(x) = log(interval(2)) * f(x)
f′ (generic function with 1 method)

julia> df(t) = ForwardDiff.derivative(f, t)
df (generic function with 1 method)

julia> f′(0) === df(0)
false

# But
julia> isequal_interval(f′(0), df(0))
true
```

The subtlety in `===` is that `df(0)` is `NG` (because of `ForwardDiff`).

**Comment by lbenet** [comment]
I will need to add tests. Perhaps it is also good time to increase the tests related to all the power functions and power modes.

**Comment by lbenet** [comment]
Followed @OlivierHnt suggestion [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/618#issuecomment-1900516668); it seems to work nicely, distinguishing literal powers from whatever. (All previous changes have been reverted.)

**Comment by OlivierHnt** [comment]
@Kolaru any thoughts?

**Comment by lbenet** [comment]
> Note (just as a memo): while `Val{n}` can have `n` to be a float or a bool, the call to `Base.literal_pow` only occurs when `n` is a literal integer which makes this implementation correct. Also, the issue is not entirely fixed for large literal integers:
> 
> ```julia
> julia> interval(1)^2305843009213693951
> [1.0, 1.0]_com
> 
> julia> interval(1)^2305843009213693952 # any integer larger than this one will also have the NG flag
> [1.0, 1.0]_com_NG
> ```
> 
> Whether or not this is a bug, it is on Julia's side.

Good catch! I will check if I can find what's going on, but I guess this is some sort of rounding issue (due perhaps to the conversion to Float64), as commented [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/618#issuecomment-1912617964).

**Comment by Kolaru** [comment]
For me it can be merged once the tests are there :)

**Comment by OlivierHnt** [comment]
At the end of test/interval_tests/power.jl, we can just add something like

```Julia
@testset "Literal powers" begin
    x = interval(1)
    n = 2
    @test isguaranteed(x ^ 2)
    @test !isguaranteed(x ^ n)
    @test_broken isguaranteed(x ^ 2.0)
    @test_broken isguaranteed(x ^ 2305843009213693952)
end
```

**Pull request merged**
