### PR TITLE
Base utilities for exact reals

### PR DESCRIPTION
**Pull request by dpsanders**
Defines `Base.hash` and `Base.isfinite` for `ExactReal`s.

This is necessary so that they work with Symbolics.jl.

### CODE REVIEW

**Comment by Kolaru** [comment]
Do you think it would be good to have tests checking the compatibility with Symbolics ? (I think you are probably the main user of Symbolics + IA, so I would say it's up to you)

**Comment by dpsanders** [comment]
Yes I think that would be great. I'm just not sure how to do that (a test-only dependency).

**Comment by OlivierHnt** [comment]
There is a Project.toml file in the test folder. You could `pkg> add Symbolics` to it.

**Comment by OlivierHnt** [comment]
Btw you should rebase this branch

**Pull request merged**
