### PR TITLE
Use BigFloat parsing for Float64 to fix Windows bug.

### PR DESCRIPTION
**Pull request by dpsanders**
Remove unnecessary `@eval`.

### CODE REVIEW

**Comment by dpsanders** [comment]
Fixes #140.

cc @kolaru

**Comment by dpsanders** [comment]
Appveyor has found another annoying rounding issue...

**Comment by dpsanders** [comment]
Probably the best way to fix this is to use 
`@static if is_windows()`
and make a version which uses BigFloat parsing as well.

**Comment by lbenet** [comment]
Regarding the changes on `atomic`, have you seen #144?

**Comment by Kolaru** [comment]
It looks like on Windowsthe rounding mode is never taken in account, so `exp(a, RoundDown)..exp(b, RoundUp)` is equivalent to `exp(a)..exp(b)`, which causes the problem.

It makes fail the `round_expr` function which relies on creating the `exp(a, RoundDown)..exp(b, RoundUp)` expression (which has then no effect on Windows). Since the `@round` uses `round_expr`, and all mathematical functions use `@round` this may affect any calculations on Windows. I do not see how the problem can be solved.

**Comment by dpsanders** [comment]
Functions like `exp` are supposed to use CRlibm, but I don't know how to get that working on Windows (would require providing a binary download), so instead they wrap the BigFloat functions.

I get this on a Windows virtual machine (finally got one working), which seems to show that it's working correctly:

```jl
julia> exp(a, RoundDown)
2.718281828459045

julia> exp(a, RoundUp)
2.7182818284590455
```

**Comment by dpsanders** [comment]
Ah, but the problem is here:
```jl
 julia> exp(709.7827128933841, RoundDown)
Inf
```

**Comment by dpsanders** [comment]
I have got tests to pass locally on 64-bit Windows using the following PR:

https://github.com/JuliaIntervals/CRlibm.jl/pull/20

!!!

**Comment by dpsanders** [comment]
Tests pass on Windows 64 on Appveyor. Windows 32 still has some weird stuff going on.

**Comment by dpsanders** [comment]
Tests pass on Appveyor on Win32 and 64!

**Comment by dpsanders** [comment]
Merging!

**Comment by lbenet** [comment]
Thanks a lot!

**Pull request merged**
