### PR TITLE
Remove @intervalbox macro

### PR DESCRIPTION
**Pull request by dpsanders**
I think we should include this in 0.9.1, @lbenet.

### CODE REVIEW

**Comment by lbenet** [comment]
This could be merged right away, but I think we should merge first https://github.com/JuliaIntervals/IntervalRootFinding.jl/pull/8, which requires some tests and docstrings, and then this one.

**Comment by dpsanders** [comment]
I'm actually not sure that the `@intervalbox` macro is that useful / necessary if all the other functions are written in the correct way.

**Comment by lbenet** [comment]
Then, I'll merge this, and we keep the discussion about having or not `@intervalbox` in https://github.com/JuliaIntervals/IntervalRootFinding.jl/pull/8

**Comment by lbenet** [comment]
Thanks, by the way!

**Comment by dpsanders** [comment]
OK, great, thanks!

**Pull request merged**
