### PR TITLE
Return IntervalBoxes for operations and functions on IntervalBoxes

### PR DESCRIPTION
**Pull request by lbenet**
Addresses #149

### CODE REVIEW

**Comment by lbenet** [comment]
Tests passed locally; but no idea how they may behave in windows.

**Comment by dpsanders** [comment]
I'm not sure we want the following:
```
julia> X = IntervalBox(3..3, 4..4)
[3, 3] × [4, 4]

julia> sin(X)
[0.14112, 0.141121] × [-0.756803, -0.756802]
```
This should really be `sin.(X)`, which still returns
```
julia> sin.(X)
2-element StaticArrays.SArray{Tuple{2},IntervalArithmetic.Interval{Float64},1,2}:
  [0.14112, 0.141121]
 [-0.756803, -0.756802]
```
This is equivalent to 
```
broadcast(sin, X)
```
so it's probably that that we should be changing.

**Comment by dpsanders** [comment]
Not sure how to do that correctly, though.
See also the comment in https://github.com/JuliaArrays/StaticArrays.jl/issues/406 about `similar_type`.

**Comment by dpsanders** [comment]
I think this will actually be easier once we do #150 .

**Comment by lbenet** [comment]
Closing in favor of #151

**Pull request closed without merging**
