### PR TITLE
Update docs deployment

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
Not important at this point because it is related with the nightly version, but worth keeping in mind since it signals a possible type unstability: https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/jobs/525408976#L547

**Comment by lbenet** [comment]
It seems that the docs generation went ok... Let's wait for all tests to complete.

**Comment by lbenet** [comment]
@dpsanders I think this is ready.

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
