### PR TITLE
Add RecipesBase as an extension

### LINKED ISSUE #605: Plotting intervals after removal of `IntervalBox`
I have often made use of `IntervalBox` for plotting enclosures of functions. With the removal of `IntervalBox` in 0.22 this is no longer possible. Is there some other convenient way of plotting interval enclosures? In the [documentation](https://juliaintervals.github.io/pages/tutorials/tutorialArithmetic/) at juliaintervals.github.io is still makes use of `IntervalBox`, but I believe that is outdated?

The removal of `IntervalBox` seems to be missing from the [NEWS.md](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/NEWS.md) file as well. As a side note it would be great to link to the NEWS.md file in the releases! It took me some time before I found it.

### PR DESCRIPTION
**Pull request by OlivierHnt**
Closes #605.

In the future we should add recipes like this for Makie.jl.

### CODE REVIEW

**Comment by lorenzgillner** [comment]
Please note that there is a typo in `ext/IntervalArithmeticRecipesBaseExt.jl`: in lines 5 and 19 `AbstractVector` is spelled incorrectly, resulting in an error when plotting boxes.

**Comment by OlivierHnt** [comment]
🤦‍♂️ my bad

**Comment by Joel-Dahne** [comment]
Looks good! Only comment I have is that it would maybe make sense to also support `BareInterval`. But I haven't really understood the new role of `BareInterval`, so it might not make sense.

**Comment by OlivierHnt** [comment]
Indeed, that crossed my mind. But I figured, it is better to be a bit conservative, at least for the time being.

An important aspect of the 0.22 versions is that one should always use `Interval` and never `BareInterval`; except perhaps in performance critical code, where the user has also a clear understanding of the operations taking place to make sense of the output.
E.g.
```Julia
julia> sqrt(bareinterval(-1, 1))
[0.0, 1.0]

julia> sqrt(interval(-1, 1))
[0.0, 1.0]_trv
```

**Pull request merged**
