### PR TITLE
Add `floatmin` and `floatmax`

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dpsanders** [comment]
What's the use case for this?

**Comment by dpsanders** [comment]
Currently there's
```jl
julia> @interval(Inf)
[1.79769e+308, ∞]
```

(Note that in general we now prefer using `interval(a, b)` instead of `@interval(a, b)` since the former is *much* faster. However, infinity is a special case.

**Comment by dlfivefifty** [comment]
I use it in the convergence check in the adaptive QR implemented in InfiniteLinearAlgebra.jl

**Comment by lucaferranti** [comment]
```
julia> @interval(Inf)
[1.79769e+308, ∞]
```

that's not the case anymore on master, it has been changed in #461

**Pull request closed without merging**
