### PR TITLE
Use fast path for sqrt and inv

### PR DESCRIPTION
**Pull request by dpsanders**
- [x] Add / define missing methods for big intervals

### CODE REVIEW

**Comment by dpsanders** [comment]
Tests are failing since e.g. `sqrt(x::Interval{BigFloat})` is no longer correctly defined.

**Comment by dpsanders** [comment]
This is ready @lbenet.

**Comment by dpsanders** [comment]
If there's no objections, I'll merge this soon and tag a patch release.

**Comment by lbenet** [comment]
There is no objection to merge this, so please, go ahead. 

(I am sorry for the delay I may have caused, but the last few days have been too busy so I have only come here as a random walker.)

**Pull request merged**
