### PR TITLE
fix: make big53() thread safe using lock

### PR DESCRIPTION
**Pull request by gwater**
Base.setprecision() is currently not marked thread safe

addresses #376

### CODE REVIEW

**Comment by gwater** [comment]
from my side this PR is complete

**Comment by Kolaru** [comment]
Could you add some inline comments with maybe a reference to #376? Since thread-safety is not explicitly tested (I can understand why) I fear we might remove the lock by mistake in the future otherwise.

**Comment by gwater** [comment]
Good point, I made the code a bit more expressive and added a note

**Comment by dpsanders** [comment]
Thanks for this! Unfortunately there's now a conflict with another just-merged PR but I'm happy to try and fix it.

**Comment by gwater** [comment]
Ok, I think the merge works now

**Comment by Kolaru** [comment]
Perfect, thanks a lot!

**Pull request merged**
