### PR TITLE
Add constructor for n-dimensional IntervalBox

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
LGTM. Is this ready to be merged?

**Comment by dpsanders** [comment]
Yes, this is ready to me merged!

**Comment by lbenet** [comment]
Great! Thanks! I'm merging!

**Comment by lbenet** [comment]
Ups... I just noticed that travis tests did not pass for Julia nightly...

**Comment by dpsanders** [comment]
I have a fix for the issue on nightly here:

https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/88

**Comment by lbenet** [comment]
#88 is already merged, so why didn't the tests pass?

**Comment by dpsanders** [comment]
#88 is open, it hasn't been merged yet?

**Comment by lbenet** [comment]
You are right, sorry for the noise. I hope I'll find some time today (or during the weekend) to take a look on this.

**Pull request merged**
