### PR TITLE
Remove inner constructor for ExactReal

### PR DESCRIPTION
**Pull request by dpsanders**
This was preventing

```
ExactReal{Int64}(3)
```
which should be allowed.

### CODE REVIEW

**Comment by OlivierHnt** [comment]
I think this was done on purpose to avoid silent errors, e.g.
```Julia
julia> ExactReal{Float64}(1//3)
ExactReal{Float64}(0.3333333333333333)
```

**Comment by Kolaru** [comment]
I think David's example should indeed be allowed, and Olivier's forbidden.

To make it so, we can add a second inner constructor:
```julia
struct ExactReal{T<:Real} <: Real
    value :: T

    ExactReal{T}(value::T) where {T<:Real} = new{T}(value)
    ExactReal(value::T) where {T<:Real} = new{T}(value)
end
```

**Comment by dpsanders** [comment]
Thanks @Kolaru, I added that inner constructor instead.

**Comment by Kolaru** [comment]
Quickly added simple tests, and LGTM, thanks :)

**Pull request merged**
